### ISSUE TITLE
Strange name files and no dimension

### ISSUE THREAD

**Issue by Le0T** [gianemi2/tinson-node#12]
Hi there, I'm trying the demo of your tinson site (http://tinson.herokuapp.com).
After I put the google drive link and the name, on my switch I see the name of the game + "uc#" at the begininng of the file name. (uc#Cuphead.nsp i.e.)

Also, the dimension of the file, on the tinfoil screen always shows me 0.0 B, I don't know if it's a tinfoil related problem.

I know that folder feature is still in beta, in fact I tried it and tinfoil shows me nothing if I add a folder to the site.

Anyway, that's a great project, keep going!

------------------------------------------------------

Ciao, sto provando la demo del tuo sito (http://tinson.herokuapp.com).
Il problema è che dopo aver messo il link di google drive ed il nome del gioco, sulla switch lo vedo con altri caratteri (uc#). In più, se provo a rinominarlo e cancello "uc" è come se non cambiasse nulla.
In più, la dimensione dei file resta 0.0 B

So anche che la feature delle cartelle gdrive è in beta, tant'è che aggiungendo la cartella, tinfoil non me la vede completamente.

Comunque complimenti per tutto il progetto!

**Comment by gianemi2** [comment]
Hi @Le0T, Thanks for using Tinson. 
That's the normal behave. Tinfoil shows them always with `uc#` before the name and the size is unknown on file browser games list. 
Once you open the file you should notice the real name in the upper left corner. I could show the dimensions in a new update. I've to check if Gdrive has API for get file size.
Thanks again for your report! 

------------------------------------------------------

Ciao @Le0T, Grazie per usare Tinson.
Quello che stai riscontrando è il comportamento normale di Tinfoil. Esso mostra sempre i file con `uc#` prima del nome e la dimensione del file è ignota di default nel file browser con Tinson. 
Una volta che hai aperto il file dovresti notare il nome reale nell'angolo in alto a sinistra dello schermo. 

Potrei mostrare le dimensioni del file in un nuovo update. Dovrei controllare se Google Drive fornisce delle API per avere la dimensione del file. 

Grazie ancora per il tuo report!

**Comment by Le0T** [comment]
If the GDrive API can let me see the dimension of the file, would be great, so I should not worry about the free space left on my switch.
Thank you for your work!

-----------------------------------------------------------------------------------------------------------

Se le API di GDrive permettessero di vedere le dimensioni del file, sarebbe una bella cosa, almeno non ci si dovrebbe preoccupare se si ha abbastanza spazio libero nella switch.
Grazie mille!

**Comment by gianemi2** [comment]
Yes. They can. And I've already implemented it in dev branch. 
When I'll be home I'll test it before deploy

----------------------------------

Si lo fanno! Ho già portato online l'aggiornamento nel branch `dev`. 
Quando sarò a casa testo se tutto funziona correttamente faccio il deploy in master.
