### ISSUE TITLE
add instructions for local hosting

### ISSUE THREAD

**Issue by FM1337** [gianemi2/tinson-node#13]
I would like to see some instructions added for deploying a local instance of this rather than just relying solely on services such as heroku

**Comment by gianemi2** [comment]
I'm sorry but I don't know how to deploying it full working on local. 
If you want to run the project just clone it and run `npm start` on `root` folder and another one on `client` folder.

I don't know how you can access from your switch to your localhost but there're a lot of guides everywhere.

**Comment by FM1337** [comment]
When I say deploying locally, I don't mean localhost, I mean deploying it to a server on either a home network, or a private VPS rather than using a public service like heroku.

**Comment by gianemi2** [comment]
Oh ok. So not locally but in your own server. 
Unfortunately I still do not know. 

You have to find some guides which fit your business. 
The required steps are:

- [ ] Clone the repository
- [ ] `$ npm install` and do it again also in client folder
- [ ] Create a mongodb database
- [ ] Populate the .env.example

I hope I've helped you a bit, 
Marco

**Comment by FM1337** [comment]
wait where's the .env.example?

**Comment by gianemi2** [comment]
> wait where's the .env.example?

I've made a merge from dev branch to master. Now master has .env.example.
