### ISSUE TITLE
scripts to convert links

### ISSUE THREAD

**Issue by costelabr17** [gianemi2/tinson-node#22]
Hi is possible to use some script to put my gdrive files link as example,
The Warlock of Firetop Mountain Goblin Scourge Edition![0100219008678000][US][v0].nsz https://drive.google.com/a/go.pasadena.edu/uc?id=14DXOPXbI8OJpr8WlE-ponF_OSuJ9Pog2&export=download

and convert like we do in tinson.herokuapp? because i have more than 3k and i want put links per file and not the whole folder ( maybe tinfoil load list fast )

PS: I try put link with this form above but no work
try manualy convert to https://docs.google.com/uc?export=download&id=14DXOPXbI8OJpr8WlE-ponF_OSuJ9Pog2 and not work too

btw i use this as exemple in tinfoil.io
 
{
    "files": ["https://url1", "sdmc:/url2", "http://url3"],
    "directories": ["https://url1", "sdmc:/url2", "http://url3"],
    "success": "motd text here"
}

**Comment by gianemi2** [comment]
I'm sorry, I've seen this message just now.

I don't know if you're already solved your issue. If not please reply here.

**Comment by costelabr17** [comment]
No problem bro, thanks for the reply but i not solved yet

**Comment by gianemi2** [comment]
Ok, so what you’re trying to achieve? Do you want a script to convert all of the google drives links in the format supported by Tinson? 

I

**Comment by costelabr17** [comment]
Yes, that is my point

**Comment by gianemi2** [comment]
Ok. Well this is not related with Tinson unfortunately. 
If you want more info and costs about it please send me a mail to: gianemi2@gmail.com <mailto:gianemi2@gmail.com>.

I’ll set this topic status as closed. If you need any other help do not esitate to open it.
