### ISSUE TITLE
Folders won't work on Tinfoil (8.1.0)

### ISSUE THREAD

**Issue by munixeclipse** [gianemi2/tinson-node#26]
I have Tinson set up using https://tinson.herokuapp.com/, but if I have folders setup, it will takes forever to load on Tinfoil, but they don't show up at all once it is opened. The folders have sharable links, and I was using folder mode. Tinfoil version is 8.1.0. This may be involved with how the folders have 1000s of NSPs in them. Is this a known issue, or is there a fix? Thanks in advance!

**Comment by munixeclipse** [comment]
I've also tried empty folders, and they have the same results.

**Comment by gianemi2** [comment]
Seems like an issue with the new Tinfoil requested URL for folders. I'm working on a fix actually.

**Comment by munixeclipse** [comment]
Thank you1

**Comment by gianemi2** [comment]
I've released the update, you can try it on [Dev Tinson](devtinson.herokuapp.com). Consider that devtinson uses a different database compared to Tinson so you may have to insert again the folders in this version.
Also I've released a new functionality which should reduce a lot the amount of time which takes Tinfoil to load. 
Please let me know if there're issues using it. 

Thank you.

**Comment by munixeclipse** [comment]
I will try the update later
