### ISSUE TITLE
How to use heroku vars as .env

### ISSUE THREAD

**Issue by KillahB33** [gianemi2/tinson-node#33]
Could you provide an example of the mongodb uri cause i can't seem to get it to work.

**Comment by gianemi2** [comment]
Seems like mongoDB has been excluded from the Heroku service. I need to check what's need changes and I'll reply ASAP.

**Comment by KillahB33** [comment]
Thanks!! I setup an Atlas cluster like they mention but I can't seem to get it to connect. I added the vars in the config section of heroku like mongo mentions but it's still not working.

**Comment by gianemi2** [comment]
Ok so I fixed it. You have to create a cluster on cloud.mongodb.com and connect using "Connect your application". Copy the URI which must be something like `mongodb+srv://`and replace the password with the one used during the cluster creation. 

After that, on the left sidebar, press on **Network Access** and click on **Add IP Address** on the top right corner. On access list entry digit 0.0.0.0/0. 

Now paste the copied URI and print on `MONGODB_URI` config vars, on Heroku. 
Press on More on the top right corner and press on Restart all dynos. 

You should have a working Tinson after these steps.
Let me know if it solves your issue.

**Comment by KillahB33** [comment]
That's what I tried but no luck, but I see yours is back up and I am ok using that one as long as you are!
Also thank you so much again for this, with JITS now down too it's getting harder and harder to find an easy way to grab stuff.
One more question, do you need the titleid in there?

**Comment by gianemi2** [comment]
Nope, you don't need the titleID, the title field is just for you. 
No problem at all, if you want to use my online version you're welcome. 

I'm going to close this thread because I think we partially solved the issue. 
Have a nice day 😃
